pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps {
        git branch: 'main',
            credentialsId: 'github-creds',   // must match the ID you set
            url: 'https://github.com/Shashankgowdasp/VivekaLoginPage-cicd.git'
      }
    }
    // other stages...
  }
}


