pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps {
        // if Jenkinsfile is already fetched via job SCM, this checkout can be redundant
        git url: 'https://github.com/Shashankgowdasp/VivekaLoginPage-cicd.git',
            credentialsId: 'github-creds',
            branch: 'master'
      }
    }
    stage('Build') {
      steps {
        echo "Static HTML project - no build step required"
      }
    }
    stage('Deploy') {
      steps {
        // Windows agent example; change to sh for Linux agent
        bat 'mkdir "%WORKSPACE%\\deploy"'
        bat 'xcopy "%WORKSPACE%\\*.*" "%WORKSPACE%\\deploy\\" /E /I /Y'
      }
    }
  }
  post {
    always { cleanWs() }
  }
}



